import 'package:equatable/equatable.dart';
import 'package:notes_app_firebase/models/note.dart';

abstract class CreateNoteEvent extends Equatable{
  const CreateNoteEvent();
@override
  List<Object?> get props => [];
}
class SubmitNoteEvent extends CreateNoteEvent{
  final Note note;
  @override
  const SubmitNoteEvent(this.note);

  @override
  List<Object?> get props => [note];
}
class EditNoteEvent extends CreateNoteEvent{
  final String noteId;
  final Note updatedNote;
  @override
  const EditNoteEvent({required this.noteId, required this.updatedNote});

  @override
  // TODO: implement props
  List<Object?> get props => [noteId, updatedNote];
}

//we used copy in sqflite to add the autogenerated id after having created the note to add the newly added autogenerated field to the already created note model.